# Generated by Django 4.0.4 on 2022-05-22 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_user_details_remove_card_user_delete_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_details',
            name='first_name',
            field=models.CharField(default='Null', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user_details',
            name='last_name',
            field=models.CharField(default='Null', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user_details',
            name='middle_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user_details',
            name='phone_number',
            field=models.CharField(default='Null', max_length=255),
            preserve_default=False,
        ),
    ]
