# Generated by Django 4.0.4 on 2022-05-22 15:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0003_user_details_first_name_user_details_last_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_details',
            name='apartment',
        ),
        migrations.RemoveField(
            model_name='user_details',
            name='card_number',
        ),
        migrations.RemoveField(
            model_name='user_details',
            name='city',
        ),
        migrations.RemoveField(
            model_name='user_details',
            name='cvc_code',
        ),
        migrations.RemoveField(
            model_name='user_details',
            name='expiry_date',
        ),
        migrations.RemoveField(
            model_name='user_details',
            name='house',
        ),
        migrations.RemoveField(
            model_name='user_details',
            name='housing',
        ),
        migrations.RemoveField(
            model_name='user_details',
            name='intercom_code',
        ),
        migrations.RemoveField(
            model_name='user_details',
            name='street',
        ),
        migrations.CreateModel(
            name='User_Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.CharField(max_length=255)),
                ('expiry_date', models.CharField(max_length=255)),
                ('cvc_code', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'User Card',
            },
        ),
        migrations.CreateModel(
            name='User_Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=255)),
                ('street', models.CharField(max_length=255)),
                ('house', models.CharField(max_length=255)),
                ('housing', models.CharField(blank=True, max_length=255, null=True)),
                ('apartment', models.CharField(blank=True, max_length=255, null=True)),
                ('intercom_code', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'User Address',
            },
        ),
    ]
