# Generated by Django 4.0.4 on 2022-05-22 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_remove_user_details_apartment_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user_address',
            options={'verbose_name_plural': 'User Addresses'},
        ),
        migrations.AlterModelOptions(
            name='user_card',
            options={'verbose_name_plural': 'User Cards'},
        ),
    ]
