# Generated by Django 4.0.2 on 2022-03-17 12:42

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('product_type', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('colors', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), size=None)),
                ('photos', django.contrib.postgres.fields.ArrayField(base_field=models.ImageField(upload_to='products'), size=None)),
                ('price', models.IntegerField()),
                ('sale_price', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Products',
            },
        ),
    ]
