# Generated by Django 4.0.2 on 2022-03-17 13:03

import django.contrib.postgres.fields
from django.db import migrations, models
import store.models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='photos',
        ),
        migrations.AddField(
            model_name='product',
            name='photo',
            field=models.ImageField(default='test', upload_to=store.models.productPath),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='colors',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), null=True, size=None),
        ),
        migrations.AlterField(
            model_name='product',
            name='sale_price',
            field=models.IntegerField(blank=True),
        ),
    ]
