# Generated by Django 4.0.4 on 2022-05-23 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_event_feedback'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order_product',
            options={'verbose_name_plural': 'Order Products'},
        ),
    ]
